name: dummy_tender
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dummyapi_repository:
    path: packages/dummyapi_repository

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  flutter_bloc: ^6.0.5
  hydrated_bloc: ^6.0.1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  lint: ^1.2.0
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  bloc_test: ^7.0.4
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

